server:
  port: 8080
  mode: debug # debug, release, test
  host: 0.0.0.0

database:
  driver: mysql # mysql, postgres
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: gin_grom
  charset: utf8mb4
  parseTime: true
  loc: Local
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

jwt:
  secret: your-secret-key
  expireTime: 24 # hours

log:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  filename: logs/app.log

cors:
  allowOrigins:
    - "*"
  allowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowHeaders:
    - "*"
  exposeHeaders:
    - "*"
  allowCredentials: true
  maxAge: 12